name:                lambda-calc
version:             0.1.0
synopsis:            The obligatory lambda calculus implementation
license:             GPL-3
author:              Tony Zorman
maintainer:          soliditsallgood@mailbox.org
homepage:            TODO

ghc-options:
  -Weverything
  -Wno-implicit-prelude
  -Wno-missing-import-lists
  -Wno-unused-packages
  -Wno-missing-safe-haskell-mode
  -Wno-all-missed-specialisations
  -Wno-unsafe
  -O2

default-extensions:
  - StrictData
  - ImportQualifiedPost
  - FlexibleContexts
  - GADTSyntax
  - OverloadedStrings
  - LambdaCase
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - BlockArguments
  - UndecidableInstances
  - InstanceSigs
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - BangPatterns

dependencies:
  - base
  - text
  - containers
  - transformers
  - mtl
  - megaparsec
  - parser-combinators

library:
  source-dirs: src

executables:
  lambda-calc:
    source-dirs: app
    main: Main.hs
    dependencies: lambda-calc

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - lambda-calc
      - hspec
